diagnostics:
  cloudStorage:
    enabled: "true"
    containerName: "playwright-assembly"

playwright1:
  browserEndpoint: "wss://eastus.api.playwright.microsoft.com/playwrightworkspaces/ea5b9ece-bbdb-4347-b2d9-49abce88373b/browsers"

windowsProxy:
  endpointUrl: "https://aegis.ilienonline.com/mvpoc/bizscraper-api"
  timeoutSeconds: "180"

fabAgent:
  captchaSolver:
    endpointUrl: "https://qslqc3tqzsfvktjk3dyn4mxhs40tyvee.lambda-url.us-east-1.on.aws/agent/captcha-solver-agent/execute"

fabDocumentTranslator:
  endpointUrl: "https://qslqc3tqzsfvktjk3dyn4mxhs40tyvee.lambda-url.us-east-1.on.aws/agent/german-document-translator/execute"
  timeoutSeconds: "60"

ingress:
  host: "devcaas-az.ilienonline.com"
  path: /mvpoc/bizscraper-api(/|$)(.*)
  tlsSecretName: ingress-tls-cert-secret

azureAd:
  instance: "https://login.microsoftonline.com/"
  tenantId: "8ac76c91-e7f1-41ff-a89c-3553b2da2c17"
  clientId: "3480eb5f-eca7-4a9c-81d2-5f65c1f77ceb"
  audience: "api://3480eb5f-eca7-4a9c-81d2-5f65c1f77ceb"

otel:
  enabled: true
  endpoint: "http://aspire-dashboard:18889"
