databaseChangeLog:
  - include:
      file: ../changelog/ddl/1.0.2603.0-create-search-audit-table.sql
      relativeToChangelogFile: true
  - include:
      file: ../changelog/ddl/1.0.2603.1-add-diagnostics-url-column.sql
      relativeToChangelogFile: true
  - include:
      file: ../changelog/ddl/1.0.2603.2-create-entity-detail-audit-table.sql
      relativeToChangelogFile: true
  - include:
      file: ../changelog/ddl/2.0.2603.0-add-state-column-to-search-audit.sql
      relativeToChangelogFile: true
  - include:
      file: ../changelog/ddl/2.0.2603.3-add-state-column-to-entity-detail-audit.sql
      relativeToChangelogFile: true
  - include:
      file: ../changelog/ddl/2.0.2603.4-add-document-storage-url-to-entity-detail-audit.sql
      relativeToChangelogFile: true
  - include:
      file: ../changelog/ddl/2.0.2603.5-add-warning-column-to-search-audit.sql
      relativeToChangelogFile: true
  - include:
      file: ../changelog/ddl/2.0.2603.6-create-script-execution-audit-table.sql
      relativeToChangelogFile: true
  - include:
      file: ../changelog/ddl/2.0.2604.0-add-caller-identity-to-search-audit.sql
      relativeToChangelogFile: true
  - include:
      file: ../changelog/ddl/2.0.2604.1-add-caller-identity-to-script-execution-audit.sql
      relativeToChangelogFile: true
